# Generated by Django 2.0.13 on 2019-05-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='kidzoneID',
            new_name='kidszoneID',
        ),
    ]
