# Generated by Django 2.0.13 on 2019-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidszone',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
