# Generated by Django 2.0.13 on 2019-05-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_kidszone_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
