# Generated by Django 2.0.13 on 2019-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0003_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidszone',
            name='upload',
            field=models.FileField(default=' ', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
