# Generated by Django 2.0.13 on 2019-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_kidszone_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kidszone',
            name='upload',
        ),
        migrations.AddField(
            model_name='kidszone',
            name='image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
